apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-cli-backups
  namespace: ecommerce-cli
  labels:
    app: ecommerce-cli
    data-type: backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-cli-audit-export
  namespace: ecommerce-cli
  labels:
    app: ecommerce-cli
    data-type: audit-export
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
