apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.3.1
          command:
            - sh
            - -c
          args:
            - cloudflared tunnel --no-autoupdate run --token "$TUNNEL_TOKEN"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: TUNNEL_TOKEN
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
